

language: node_js
node_js: node
cache:
  directories:
  - node_modules
env:
- CI=true
deploy:
  provider: heroku
  #api_key:
  #app: morning-waters-27863
  on:
    repo: WingChhun/react-redux-sass-boilerPlate